# Generated by Django 2.0.dev20170906232138 on 2017-09-07 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='created_at',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
