# Generated by Django 2.0.dev20170906232138 on 2017-09-07 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_account_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
