# Generated by Django 2.0.dev20170906232138 on 2017-09-11 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20170907_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'managed': False},
        ),
    ]
