# Generated by Django 2.0.dev20170906232138 on 2017-09-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('address', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=121)),
                ('salary', models.IntegerField()),
            ],
            options={
                'db_table': 'employees',
                'managed': False,
            },
        ),
    ]
