# Generated by Django 2.0.dev20170906232138 on 2017-09-20 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={},
        ),
    ]
